export interface ChangelogEntry {
  version: string;
  date: string;
  title?: string;
  changes: {
    type: "added" | "changed" | "fixed" | "removed";
    description: string;
  }[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "2.5.2",
    date: "2026-03-20",
    title: "Webhook dropdown overflow fix",
    changes: [
      {
        type: "fixed",
        description:
          "Fixed webhook Standard Mode and Realtime Mode dropdowns pushing the settings panel content beyond the visible area when a long option was selected. The selected value now truncates with an ellipsis and shows the full text in a tooltip on hover.",
      },
    ],
  },
  {
    version: "2.5.1",
    date: "2026-03-18",
    title: "Form output card overflow, fullscreen view & server-side exception fix",
    changes: [
      {
        type: "added",
        description:
          "Fullscreen button for the form output card (desktop only) — expand the form to a full-screen dialog for easier editing, matching the transcript card's fullscreen behavior.",
      },
      {
        type: "fixed",
        description:
          "Form output card in Standard mode no longer overflows — content is now contained within the card with scrollable form fields and always-visible action buttons pinned at the bottom.",
      },
      {
        type: "fixed",
        description:
          "Fixed a server-side exception that occurred when opening the app in a new browser or incognito window — caused by Auth.js cookie writes inside server components. Auth checks are now handled entirely in the proxy middleware.",
      },
    ],
  },
  {
    version: "2.5.0",
    date: "2026-03-17",
    title: "Webhook transcript title, manual Fire Webhook button & new trigger option",
    changes: [
      {
        type: "added",
        description:
          'New "Generate title for transcript" toggle in webhook settings. When enabled, transcript webhooks generate a concise title via LLM before firing — a "Webhook queued" notification appears while the title is being generated. Includes a customizable title prompt editor and a dedicated Feature-Specific Model override ("Webhook Transcript Title") so you can use a different/cheaper model for title generation.',
      },
      {
        type: "added",
        description:
          'Manual "Fire Webhook" button in the Speaker Mapping section. Sends a transcript webhook on demand with the current speaker mapping. If unmapped speakers are detected (e.g. "Speaker A"), a confirmation dialog asks before firing.',
      },
      {
        type: "added",
        description:
          'New Standard mode webhook trigger: "After Transcript (speaker mapping) & Summary". Automatically fires the transcript webhook after speaker names are applied via Apply Names, ensuring the payload includes the speaker mapping. The summary webhook still fires normally after summary generation.',
      },
      {
        type: "changed",
        description:
          "Webhook summary_title is no longer extracted from the first line of the summary — it is now independently generated by the LLM, guaranteeing a concise, descriptive title for every summary.",
      },
      {
        type: "changed",
        description:
          'Test webhook now sends the full summary.completed payload schema (with sample data) instead of a minimal ping — makes it easier to validate your webhook receiver against the real payload shape. The event is set to "test.completed" and mode to "test" so receivers can distinguish test payloads from real ones.',
      },
      {
        type: "changed",
        description:
          'Renamed Standard mode trigger "After Transcript & Summary" to "After Transcript (immediately) & Summary" for clarity — behaviour is unchanged.',
      },
      {
        type: "fixed",
        description:
          "Transcript card in Standard mode step 2 no longer grows unbounded to fit the full transcript — the card is now capped in height with scrollable content inside.",
      },
      {
        type: "fixed",
        description:
          "Summary card in Standard mode step 3 no longer extends to fit the full content — both the transcript and summary cards now share the same fixed height with independently scrollable content.",
      },
    ],
  },
  {
    version: "2.4.0",
    date: "2026-03-16",
    title: "Webhook enhancements, connection testing & Azure OpenAI fix",
    changes: [
      {
        type: "added",
        description:
          "Webhook Custom Arguments — add optional key-value pairs in Settings > Webhooks that are included in every webhook payload under data.user_args. Useful for passing metadata like team IDs, environment tags, or routing keys to your webhook receiver.",
      },
      {
        type: "added",
        description: 'Webhook payloads now include a summary_title field when the content type is "summary".',
      },
      {
        type: "added",
        description:
          "Test Connection button in AI Model settings — sends a quick ping to verify your LLM provider credentials and model are working. Shows a green indicator on success or a red indicator with error details on failure.",
      },
      {
        type: "added",
        description:
          "Test Webhook button in Webhook settings — fires a test payload to your configured webhook URL to verify it is reachable. Includes any custom arguments in the test payload.",
      },
      {
        type: "fixed",
        description:
          "Fixed Azure OpenAI not working when selected as the LLM provider — the model field was sent as an empty string instead of the deployment name, causing a validation error.",
      },
    ],
  },
  {
    version: "2.3.0",
    date: "2026-03-15",
    title: "Redesigned UI",
    changes: [
      {
        type: "changed",
        description:
          "Updated the overall design of the application with a cleaner and more modern look & improved typography.",
      },
    ],
  },
  {
    version: "2.2.0",
    date: "2026-03-14",
    title: "Webhook support & display name",
    changes: [
      {
        type: "added",
        description:
          "Webhooks — automatically send transcripts, summaries, and form outputs to external systems (Slack, Notion, n8n, CRMs, etc.) via HTTP POST. Configure a webhook URL and optional HMAC signing secret in Settings > Webhooks (requires Advanced Settings). Standard mode supports firing after summary only or after both transcript and summary. Realtime mode supports firing when the session stops, after the final summary, or only when a final summary is enabled. Webhook settings can also be configured via the chatbot.",
      },
      {
        type: "added",
        description:
          'Your Name — set your name in Settings > Features > General (defaults to your Google account name). The chatbot uses this to understand who "I" / "my" refers to in transcripts, so you can ask questions like "What are my action items?" instead of referring to yourself by name.',
      },
    ],
  },
  {
    version: "2.1.0",
    date: "2026-03-13",
    title: "Newline speaker format support & Realtime aggregation fix",
    changes: [
      {
        type: "added",
        description:
          'Speaker Mapping now supports a second transcript format — speaker names on their own line followed by text on the next line (e.g., "Speaker 1", "Max Mustermann", "Microphone"). This newline format is detected automatically when no colon-format speakers are found. Renaming only updates speaker label lines, not occurrences of the name within the spoken text. (Format used by MacWhisper)',
      },
      {
        type: "fixed",
        description:
          "Realtime Precise mode — consecutive transcript blocks from the same speaker are now properly aggregated into a single block, even when some utterances arrive without a speaker label. Also fixes overlapping text at speaker boundaries when speakers talk without pauses.",
      },
    ],
  },
  {
    version: "2.0.0",
    date: "2026-03-08",
    title: "Added timestamps, speaker mapping, keyterms prompting & UI polish",
    changes: [
      {
        type: "added",
        description:
          "Timestamps are now displayed for each utterance in the transcript view — Standard mode uses precise timestamps from AssemblyAI, Realtime mode uses wall-clock elapsed time. Toggle visibility in Settings > Features under Standard and Realtime sections.",
      },
      {
        type: "added",
        description:
          "Speech Model toggle in Settings > Features > Realtime — choose between Fast (word-by-word streaming, no timestamps, no speaker labels) and Precise (turn-based streaming with speaker diarization & timestamps). Consecutive utterances from the same speaker are automatically merged in Precise mode.",
      },
      {
        type: "added",
        description:
          "Speaker Mapping for Realtime mode — map generic speaker labels (Speaker A, Speaker B) to real names via a new dialog accessible from the transcript header. Mappings apply to existing and future utterances. Includes key point extraction and auto-suggested names (configurable in Settings).",
      },
      {
        type: "added",
        description:
          "Keyterms Prompting — create named lists of domain-specific terms (e.g., company names, technical jargon) to improve transcription accuracy. Manage lists in Settings > Features > General (requires Advanced Settings). Works with both Standard and Realtime modes, and keyterms lists can be switched mid-session in Realtime mode.",
      },
      {
        type: "added",
        description:
          "Reset All Settings to Defaults — a new button at the bottom of the Settings panel lets you revert all settings to their factory defaults with a single click. A confirmation dialog is shown before resetting. API keys are not affected.",
      },
      {
        type: "added",
        description:
          'Unfilled fields popover — hover (desktop) or tap (mobile) the "X/Z filled" badge on any form output to see which fields are still unfilled. Works in both Standard and Realtime mode.',
      },
      {
        type: "changed",
        description:
          "Realtime incremental summaries now skip if fewer than 5 new words have been added to the transcript since the last update, avoiding unnecessary API calls during silence or pauses.",
      },
      {
        type: "fixed",
        description:
          "Standard mode form template layout — the transcript card now matches the form card height and scrolls internally instead of stretching the page. Button alignment between transcript and form cards is now consistent.",
      },
      {
        type: "fixed",
        description:
          "Summary auto-scroll during streaming — scrolling up now pauses auto-scroll so you can read earlier content while the summary is still generating. Scrolling back to the bottom re-enables it.",
      },
      {
        type: "fixed",
        description:
          "Fullscreen transcript view — content no longer overflows the dialog and is now properly scrollable. Fixed in both Standard and Realtime mode. Copy/Save buttons are now also available in fullscreen.",
      },
    ],
  },
  {
    version: "1.10.0",
    date: "2026-03-04",
    title: "Independent refresh for Questions & Form Output in Realtime mode",
    changes: [
      {
        type: "added",
        description:
          "Added independent refresh buttons to the Questions & Topics and Form Output sections in Realtime mode — re-evaluate questions or re-fill forms at any time without triggering a full summary refresh.",
      },
      {
        type: "added",
        description:
          'Added a "Re-evaluate Answered Questions" setting under Settings > Features > Realtime — when enabled, the manual Questions refresh also re-evaluates already answered questions against the latest transcript.',
      },
    ],
  },
  {
    version: "1.9.0",
    date: "2026-03-03",
    title: "Simplified settings panel for new users",
    changes: [
      {
        type: "added",
        description:
          "Added an Advanced Settings toggle in Settings > Features > General — when off, only essential settings are shown: API Keys, AI Model, and the toggle itself. Power users can enable it to access all configuration options.",
      },
    ],
  },
  {
    version: "1.8.0",
    date: "2026-03-01",
    title: "Chatbot copy format settings, smarter synced mode switching & improved copy button accessibility",
    changes: [
      {
        type: "added",
        description:
          "The chatbot can now change Default Copy Format, Default Save Format, and Default Chatbot Copy Format on behalf of the user. A new configurable Chatbot Copy Format setting controls how chatbot messages are copied to the clipboard (Formatted Text, Plain Text, or Markdown), defaulting to Formatted Text.",
      },
      {
        type: "changed",
        description:
          "Switching to Standard mode after a synced recording started from Realtime now shows the Record Audio tab instead of the previously saved step position",
      },
      {
        type: "changed",
        description:
          "Chatbot copy button now appears at both the top and bottom of long assistant messages that overflow the visible area, so you no longer need to scroll back up to copy",
      },
    ],
  },
  {
    version: "1.7.0",
    date: "2026-02-28",
    title:
      "Added more ways to copy output, added download functionality, added token usage tracking, step persistence in standard mode & fixed iOS microphone permission prompts",
    changes: [
      {
        type: "added",
        description:
          'Unified "Copy as" and "Save as" split buttons across all output sections — copy in 4 formats (Formatted, Plain Text, Markdown, JSON) and download in 6 formats (.txt, .md, .docx, .pdf, .html, .json) with configurable defaults in Settings',
      },
      {
        type: "added",
        description:
          "Added token usage tracking for AI requests in the chatbot, summary & added an AI usage section in the profile page to view total tokens used over the past week/month/year",
      },
      {
        type: "changed",
        description:
          "Standard mode now remembers your last viewed step (Upload, Transcript, or Summary) across page reloads and devices",
      },
      {
        type: "fixed",
        description:
          'Skipped the early microphone permission prompt on iOS to avoid repeated prompts on every page load — iOS Safari has no "Always Allow" option, so permission is now only requested when starting a recording or realtime session',
      },
    ],
  },
  {
    version: "1.6.0",
    date: "2026-02-27",
    title: "Smart date detection, chatbot quick-apply actions & draft persistence",
    changes: [
      {
        type: "added",
        description:
          "Meeting date is now auto-detected from the uploaded audio filename (e.g. 2024_01_15_standup.mp3) — supports yyyy-MM-dd, dd-MM-yyyy, and yyyyMMdd patterns",
      },
      {
        type: "added",
        description:
          'Chatbot quick-apply: start your message with "!" to skip the action confirmation step and apply it immediately (e.g. "!Switch to light mode")',
      },
      {
        type: "added",
        description: "The chatbot can now perform more actions on behalf of the user",
      },
      {
        type: "changed",
        description:
          "Sync mode now shows confirmation dialogs when the other mode has existing data (ended realtime session or completed recording) instead of silently skipping — also fixed display audio not being captured in Standard when auto-started from Realtime",
      },
      {
        type: "changed",
        description:
          "Chatbot input text now persists when closing and reopening the chat window — draft is only cleared when sent or when clearing the conversation",
      },
      {
        type: "fixed",
        description:
          "Export/Import Settings dialog is now scrollable on mobile devices, fixing the QR code being cut off on smaller screens",
      },
      {
        type: "removed",
        description:
          "Temporarily disabled OpenAI models (GPT-5.2, GPT-5.2 Pro) for the Langdock provider due to a proxy bug on Langdock's side — use Claude instead",
      },
    ],
  },
  {
    version: "1.5.2",
    date: "2026-02-26",
    title: "Improved chatbot capabilities, simplified transcript context and suspend/reattach",
    changes: [
      {
        type: "added",
        description:
          'The chatbot now knows the user\'s current time and last visit timestamp, allowing it to answer questions like "What time is it?" and "What has changed since my last visit?" by correlating visit history with the changelog',
      },
      {
        type: "changed",
        description:
          'Detaching the transcript in the chatbot now suspends it instead of removing it entirely — the badge stays visible in a dimmed "Transcript paused" state with a reattach button to resume using it',
      },
      {
        type: "changed",
        description:
          "Clicking Start or Continue Session in Realtime mode now shows a confirmation dialog when existing transcript or summary data is present — choose to continue with existing data, clear only transcript and summary, or clear all session data including questions, form output, and template selection",
      },
      {
        type: "removed",
        description:
          'Simplified the chatbot Transcript Context setting by removing the "Current mode" / "Latest transcript" selector — the chatbot now always uses the transcript from the active mode',
      },
    ],
  },
  {
    version: "1.5.1",
    date: "2026-02-26",
    title: "Stability improvement",
    changes: [
      {
        type: "fixed",
        description:
          "Fixed an issue where transcription and AI requests could occasionally fail when multiple actions were performed at the same time due to synchronous code execution blocking the main thread",
      },
    ],
  },
  {
    version: "1.5.0",
    date: "2026-02-26",
    title:
      "Added session persistence, maximizable chatbot, sync standard/realtime mode, and QR code generation for API keys",
    changes: [
      {
        type: "added",
        description:
          "Added session persistence feature that allows the user to refresh the page or close and reopen the application without losing their current transcript, summary, chatbot conversation, etc.",
      },
      {
        type: "added",
        description:
          "The chatbot now has a maximize button that allows the user to expand the chatbot window to take up more space on the screen for easier interaction and better visibility of the conversation history (desktop only)",
      },
      {
        type: "added",
        description:
          "Sync Standard + Realtime mode: enable in Settings to run both recording modes in parallel with a shared microphone. Starting one mode auto-starts the other, pause/resume stay in sync, and a confirmation dialog coordinates stopping",
      },
      {
        type: "added",
        description:
          "QR code generation for API keys: quickly transfer your API keys to another device by scanning a QR code instead of typing them manually",
      },
      {
        type: "changed",
        description: "The microphone device is now shared between the normal/realtime mode and the chatbot",
      },
      {
        type: "fixed",
        description:
          "Previously the connection circle indicator in the realtime mode did not accurately reflect wheter the realtime API was ready to transcribe or not. This has been fixed.",
      },
    ],
  },
  {
    version: "1.4.0",
    date: "2026-02-25",
    title:
      "Added form output and export/import settings + api keys [optional] as well as session persistence for transcript and summary",
    changes: [
      {
        type: "added",
        description:
          "Form output feature lets users create form templates with custom fields that can be filled out with the extracted data from the transcript. Works in normal and realtime mode",
      },
      {
        type: "added",
        description:
          "Export and import settings feature that allows users to export their current settings and optionally API keys as a encoded string, and import them back into the application when needed",
      },
      {
        type: "added",
        description:
          "The latest transcript & summary will now be saved automatically and persist across sessions",
      },
    ],
  },
  {
    version: "1.3.0",
    date: "2026-02-24",
    title: "Added automatic speaker labels",
    changes: [
      {
        type: "added",
        description:
          "Automatic speaker labels feature that let's the AI try to label the speakers based on the given transcript. Can be toggled in the settings panel. Enabled by default",
      },
    ],
  },
  {
    version: "1.2.1",
    date: "2026-02-24",
    title: "Chatbot feature improvements",
    changes: [
      {
        type: "changed",
        description:
          "Changed the behaviour of the live transcript feature to establish the websocket connection immediately when the chatbot is opened, allowing for faster response times and a more seamless user experience",
      },
      {
        type: "fixed",
        description:
          "Sometimes after a pause the text got cleared from the input field during dictation mode. This has been fixed and the text will now remain in the input field even after a pause in dictation",
      },
    ],
  },
  {
    version: "1.2.0",
    date: "2026-02-24",
    title: "Added chatbot feature",
    changes: [
      {
        type: "added",
        description:
          "Chatbot feature with conversation history, context awareness & the ability to perform actions on behalf of the user",
      },
      {
        type: "added",
        description: "Paste button in API key manager for easy input of API keys from clipboard",
      },
      {
        type: "changed",
        description: "Added simple plausability check for API keys to ensure they are in the correct format",
      },
    ],
  },
  {
    version: "1.1.0",
    date: "2026-02-23",
    title: "Added release notes and changelog",
    changes: [{ type: "added", description: "Release page with changelog and version history" }],
  },
  {
    version: "1.0.0",
    date: "2026-02-22",
    title: "Initial Release",
    changes: [{ type: "added", description: "Initial release of the application" }],
  },
];
